### Driving `kraken.exe` end to end: write the `.env`, run the binary, read the `.mod` and `.prt`.

"""
    FortranKrakenError

Raised when a Fortran KRAKEN run fails. Carries the error text the binary printed, because that is
the only useful diagnostic it produces — see [`run_fortran_kraken`](@ref) for why the exit code is
not one.
"""
struct FortranKrakenError <: Exception
    binary::String
    detail::String
    report::String
end

function Base.showerror(io::IO, e::FortranKrakenError)
    print(io, "FortranKrakenError: ", basename(e.binary), " failed.\n", e.detail)
    return nothing
end

# ERROUT (misc/FatalError.f90) prints a three-line block into the .prt and then STOPs:
#
#      *** FATAL ERROR ***
#      Generated by program or subroutine: <where>
#      <message>
#
# Some failures print an ERROR line without the banner, so both are collected.
function _error_lines(report::AbstractString)
    lines = strip.(split(report, '\n'))
    fatal = findfirst(l -> occursin("FATAL ERROR", uppercase(l)), lines)
    if fatal !== nothing
        block = filter(!isempty, lines[fatal:min(end, fatal + 3)])
        return String.(block)
    end
    return String.(filter(l -> occursin("ERROR", uppercase(l)), lines))
end

function _warning_lines(report::AbstractString)
    return String.(filter(l -> occursin("warning", lowercase(l)), strip.(split(report, '\n'))))
end

function _resolve_cmd(bindir, complex::Bool)
    bindir === nothing && return kraken_cmd(; complex=complex)
    exe = joinpath(String(bindir), _exe_name(complex))
    isfile(exe) || error("No $(_exe_name(complex)) in $bindir")
    return Cmd([abspath(exe)])
end

"""
    run_fortran_kraken(env, freq; complex=false, bindir=nothing, keep_files=false, kwargs...)

Run unmodified Fortran KRAKEN on `env` and return its solution.

Writes a `.env` into a temporary directory, invokes `kraken.exe` (or `krakenc.exe` when
`complex=true`) with the file root as its single command-line argument, then reads back the `.mod`
mode file and the `.prt` group-speed table.

For a scalar `freq` this returns one named tuple; for a vector it does a single broadband run and
returns one named tuple per frequency, in the order given. Each has:

- `kᵣ`, `ϕ`, `depths`, `nmodes` — from the `.mod`, as [`read_mod_file`](@ref) returns them.
- `grp` — the `.prt` group-speed table ([`read_grp`](@ref)), or `nothing` if there is none. Its
  `kᵣ` carries more digits of the *real* part than the `.mod` does; see
  [`MOD_WAVENUMBER_DIGITS`](@ref). Its `v` is empty of information unless
  [`has_group_speeds`](@ref) says otherwise.
- `warnings` — every `Warning` line from the `.prt`. These are not fatal but they are worth
  surfacing: "Mesh too coarse to sample the modes adequately" means the answer is suspect.
- `dir` — the run directory when `keep_files=true`, otherwise `nothing`.

Extra keyword arguments are forwarded to [`write_env_file`](@ref), so `clow`, `chigh`, `rd`,
`nmesh`, `title` and friends all work here.

# Errors

`kraken.exe` **exits 0 even on a fatal error** — it writes `*** FATAL ERROR ***` into the `.prt`,
prints `STOP Fatal Error: Check the print file for details` on stderr, and stops with a zero status.
Checking the exit code would therefore pass every failed run and then fail confusingly on a missing
`.mod`. This function scans the `.prt` instead and throws a [`FortranKrakenError`](@ref) quoting the
Fortran's own message.

The temporary directory is removed even when the run fails, unless `keep_files=true` — which keeps
it on failure too, that being exactly when you want to look at it.
"""
function run_fortran_kraken(env, freq; complex::Bool=false, bindir=nothing, keep_files::Bool=false, kwargs...)
    freqs = freq isa Real ? [Float64(freq)] : Float64.(collect(freq))
    isempty(freqs) && error("At least one frequency is required")
    cmd = _resolve_cmd(bindir, complex)
    binary = first(cmd.exec)

    dir = mktempdir()
    try
        root = joinpath(dir, "case")
        write_env_file(root, env, freq; kwargs...)

        stderr_buf = IOBuffer()
        run(pipeline(ignorestatus(Cmd(`$(cmd) case`; dir=dir)); stdout=devnull, stderr=stderr_buf))
        stderr_text = strip(String(take!(stderr_buf)))

        prt = root * ".prt"
        report = isfile(prt) ? read(prt, String) : ""
        problems = _error_lines(report)
        if !isempty(problems)
            throw(FortranKrakenError(binary, join(problems, "\n"), report))
        end
        if isempty(report)
            throw(
                FortranKrakenError(
                    binary,
                    "The binary produced no .prt file at all." * (isempty(stderr_text) ? "" : "\nstderr: $stderr_text"),
                    report,
                ),
            )
        end
        if !isfile(root * ".mod")
            throw(
                FortranKrakenError(
                    binary,
                    "The run reported no error but wrote no .mod file." *
                    (isempty(stderr_text) ? "" : "\nstderr: $stderr_text"),
                    report,
                ),
            )
        end

        warnings = _warning_lines(report)
        results = map(freqs) do f
            modes = read_mod_file(root * ".mod"; freq=f)
            grp = try
                read_grp(prt; freq=f)
            catch
                nothing
            end
            return (; modes..., grp, warnings, binary, dir=keep_files ? dir : nothing)
        end
        return freq isa Real ? only(results) : results
    finally
        keep_files || rm(dir; recursive=true, force=true)
    end
end
